engines:
  checkstyle:
    enabled: true
    checks:
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.LocalVariableNameCheck:
        enabled: false
  fixme:
    enabled: true

