engines:
  checkstyle:
    enabled: true
    checks:
      # disable javadoc checks for this repo
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck:
        enabled: false
      # disable name checks for this repo
      com.puppycrawl.tools.checkstyle.checks.naming.LocalVariableNameCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.ParameterNameCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.MemberNameCheck:
        enabled: false
      # allow multiple variables to be declared on one line in this repo
      com.puppycrawl.tools.checkstyle.checks.coding.MultipleVariableDeclarationsCheck:
        enabled: false
  fixme:
    enabled: true

